{% set version = "2.6.2" %}
{% set sha256 = "adf690c730f31685f9c4d6d8bb470541e62f31380355f741327b9fea9ee0b43e" %}

package:
  name: digital_rf
  version: {{ version }}

source:
  url: https://github.com/MITHaystack/digital_rf/releases/download/{{ version }}/digital_rf-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 1
  run_exports:
    - {{ pin_subpackage('digital_rf') }}

requirements:
  build:
    - {{ compiler('c') }}
    - cmake >=3.0

  host:
    - hdf5
    - mako
    - numpy
    - pkgconfig
    - python
    - setuptools

  run:
    - gnuradio  # [(not win) and py27]
    - h5py
    - hdf5
    - matplotlib
    - {{ pin_compatible('numpy') }}
    - packaging
    - pandas
    - python
    - python-dateutil
    - pytz
    - scipy
    - six
    - watchdog

test:
  requires:
    - pytest >=3.6
  imports:
    - digital_rf
    - digital_rf.digital_rf_hdf5
    - gr_digital_rf  # [(not win) and py27]
  source_files:
    - python/tests/*.py
    - python/examples/*.py
  commands:
    - pytest
    - python python/examples/example_write_digital_metadata.py
    - python python/examples/example_read_digital_metadata.py
    - conda inspect linkages -p $PREFIX digital_rf  # [not win]
    - conda inspect objects -p $PREFIX digital_rf  # [osx]

about:
  home: https://github.com/MITHaystack/digital_rf
  license: BSD
  license_file: LICENSE
  summary: 'Work with data in the Digital RF and Digital Metadata formats.'
  description: |
    The Digital RF project encompasses a standardized HDF5 format for reading
    and writing of radio frequency data and the software for doing so. The
    format is designed to be self-documenting for data archive and to allow
    rapid random access for data processing. For details on the format, refer
    to the documentation.

    This suite of software includes libraries for reading and writing data in
    the Digital RF HDF5 format in C (``libdigital_rf``), Python
    (``digital_rf``) with blocks for GNU Radio (``gr_digital_rf``), and
    MATLAB. It also contains the `thor` UHD radio recorder script, Python
    tools for managing and processing Digital RF data, example scripts that
    demonstrate basic usage, and example applications that encompass a
    complete data recording and processing chain for various use cases.

  doc_url: https://github.com/MITHaystack/digital_rf/tree/master/docs
  dev_url: https://github.com/MITHaystack/digital_rf

extra:
  recipe-maintainers:
    - ryanvolz
