{% set version = "2.5.2rc1" %}
{% set sha256 = "2e83186227cbebf197ceb31dba89e136063a288a13481658ed897546a724b7be" %}

package:
  name: digital_rf
  version: {{ version }}

source:
  url: https://github.com/MITHaystack/digital_rf/archive/{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  skip: True  # [win]
  detect_binary_files_with_prefix: True

requirements:
  build:
    - toolchain
    - cmake >=3.0
    - setuptools
    - python >=2.7,<3
    - numpy x.x
    - hdf5 1.8.18|1.8.18.*
    # gnuradio requirements
    - gnuradio
    - boost 1.64.*
    - swig
    - log4cpp
  run:
    - python >=2.7,<3
    - hdf5 1.8.18|1.8.18.*
    - numpy x.x
    - h5py
    - gnuradio
    - matplotlib
    - scipy
    - watchdog
    # extra requirements for thor script
    - pytz
    - dateutil
    # gnuradio requirements
    - boost 1.64.*
    - log4cpp

test:
  imports:
    - digital_rf
    - digital_rf.digital_rf_hdf5
    - gr_drf
  source_files:
    - tests/*.py
    - examples/*.py
  commands:
    - python tests/test_digital_rf_hdf5.py
    - rm -r /tmp/hdf5*
    - python examples/example_write_digital_metadata.py
    - python examples/example_read_digital_metadata.py
    - rm -r /tmp/test_metadata/

about:
  home: https://github.com/MITHaystack/digital_rf
  license: BSD
  license_file: LICENSE
  summary: 'Work with data in the Digital RF and Digital Metadata formats.'
  description: |
    The Digital RF project encompasses a standardized HDF5 format for reading
    and writing of radio frequency data and the software for doing so. The
    format is designed to be self-documenting for data archive and to allow
    rapid random access for data processing. For details on the format, refer
    to the documentation.

    This suite of software includes libraries for reading and writing data in
    the Digital RF HDF5 format in C (``libdigital_rf``) and Python
    (``digital_rf``), with optional interfaces for GNU Radio (``gr_drf``) and
    MATLAB. It also contains the `thor` UHD radio recorder script, Python tools
    for managing and processing Digital RF data, example scripts that
    demonstrate basic usage, and example applications that encompass a complete
    data recording and processing chain for various use cases.

  doc_url: https://github.com/MITHaystack/digital_rf/tree/master/docs
  dev_url: https://github.com/MITHaystack/digital_rf

extra:
  recipe-maintainers:
    - ryanvolz
