channels:
  # only used for README generation, see recipe/conda_build_config.yaml
  targets:
  - [ryanvolz, main]
github:
  user_or_org: ryanvolz
travis:
  secure:
    BINSTAR_TOKEN: pR74wmZxwbvoTnRPi2vVGlEDxJyCqZFq2AsTtGXhpMRrmPVrPmnCKRYO7GNbxbvdUDnbuL/+NFIz+okF5YXRoqtB/h/0WIrd8csNnAS57h426HTYZ27aszyDpQQEybE4V74Tenyq9EhN9quWNYFnhWHkvO9TDpSf6wVwq+O8522R/pPVkUz65ZAYqs7tLAdTfcUTGuc1OQsF0HHkxueuN6l9GqRiZjoyKAOO66kfVF2H69+qfMFivIkR7udDcoeW6+uVlC5CoGyxPiZ4WUrtLFNWpRchBssg8skpi0W86h+mN6wZVYo9bnHbajIy0lcThaeH8FPPDMU6uF+tt+QpLOfjHRNUBTTil8MmpVT714IMZC7y+XhlD2X0pEGQuAS5ttnN5B6BBeUpT/Wo1aK/N0x3yoAi/557IHmL19mCntIg4kWdQPIDcISZjxuEMlTmpAk3ygj20uCaDDr67Kc0hGfdAoks8ohGrNNRp7al5pdnWwFVJWcujGH5tzTxcSHTQkG15vy8wVDp+ezzKt4la2O5Qh3KqDvdZc2VRD55XGT0DdZRyarGAbl0CXASwi1ZawpiOXFfuKuKp+/Getwh3AhJ5tIvG8BDSdMv1hHEoBMfUMQAMmib29ahboyL4nJEnkDP1u3t8KFvyXhJHgygJlPGymahk2yGQ4l55Tqz3Fo=
appveyor:
  secure:
    BINSTAR_TOKEN: 71TfwwHlSXL1lpYe3qfRuCAgxnXZkZw1a89oCIgAz4T+pKtbztMaAfWiC4oMSy2B
