channels:
  sources:
  - conda-forge
  - ryanvolz
  - defaults
  targets:
  - [ryanvolz, main]
github:
  user_or_org: ryanvolz
travis:
  secure:
    BINSTAR_TOKEN: d0JYANGHJAxBR9LdwVpaAsHQLBgS1y1Pbg714XVgmZ+cd9dqOwURI12cceGxM6bwQAk7f6SKpTWrBD+HprBsyzp5IrBIid+IsHU0JiR2ywQJBUH1WB4hYzrMD2QCeUHWDyNvhg1UD/WDUE0N2IUlHcNAdrOJouUcNRSwpNlwwmFV0Fa1stQ/QXKhPw7JbjoyWbxHCMrD2S2o8ovx28gsWD2WQodlyJLzJTMRq6e8Wr/5UNZ1UGq3BNPwYEbQKVMYpEgNnLwbMXKmzUE8Kts02ZQz4IA/51f8j3U9ZuXif8J/BfzTa7SVlcH3sc/O0WTsJ/xOCP0hvnj1eBQCmKMyt002KtyxVo4xV/z424l6LQJrRnemmu2qJSboL/ciJ+ioVHRQTY8tTBlQVmwU6FMEg/bGz4TmXWVHKEfQQreLBcC/8S4VmJtQXFIW7qMYHHvKof8mSesqUQIXQpWH3GMwH42PgL8QKrplQBf4O2+RsWwzGWllbi3S8c6sqAq4uZQsg5psXGGn1o9pRX5ptbxMWIlCxexOR4+QKu57IQgEh/VL3SvNgpZ2+aUC/GnEigGv3tRqDV2OaPC81QgT+S3jrxnhraV4fEo24IXOm4tuZs6gno9JvDNLzwzoVerGV1UaD/fG5FPrfaIy/ZMYEDM2V2BKVKpJki5kjusFbyx1ltY=
appveyor:
  secure:
    BINSTAR_TOKEN: 71TfwwHlSXL1lpYe3qfRuCAgxnXZkZw1a89oCIgAz4T+pKtbztMaAfWiC4oMSy2B
