channels:
  # only used for README generation, see recipe/conda_build_config.yaml
  targets:
  - [ryanvolz, main]
github:
  user_or_org: ryanvolz
provider:
  linux: azure
  osx: azure
  win: azure
travis:
  secure:
    BINSTAR_TOKEN: BckZGoSRDg+OABSpRCsqFG9D1i03EkNmFQH5zxhKZnvANcNTrfIn7VHdt+hfTUhZ+pmZ4se4UwNOgZqH9LoNFKnaXqPX7FQBTnd6qTMMu2pPZtOcPDQUA/A2Fm5Nk2AlfxqHYpPjm18XupDBlixR1SYwLThAfz8eUAzKi4WmRpp1wZ2/Q1gYlagoPBTYd5JHAd+mlEJ2LVqrGE670kmBN6ukMu+YHYtFpE+I8jjYRFvdmpJGExZ2jPsuW9qoyQZikaME+MWWKnXMbelY3SloRpLoDNe1EprLmYrjgM6Ix4ZNDCfQIJGzBdq6gqOkd3j7toTKnIzFp/CDmYWxFuHCl0G1BQZb8d+8fFDTjyUKLaN7Y/3Ot0bf8U07FWo2UMYj58bjEbgSHtrgyjzUBXVprNna9nj5+CvNwKnWgJbZQ2TrsWtqGZxfYkJcvlf9rJvpYpQ/56mpfErlZNZ6sDrMju49CVCwmhGlRPWKS5Y4jPHszJjL4ED4iekwS+BzK2EPcIVdT97yzxQHty+leh8gajRxgh7tapvJKU/90PQi0U78GWKVUs6v6jgZLE01qoRypZtntirK4fZi4FKMVnoUn3AeaNxiBWGZ0L7v5DYd4HjF1Fw3UnvKGO/EFlPiPUPE1HolmlVasczGqqYNPGFFK8SNTeCBm2hHTehC3njwSas=
appveyor:
  secure:
    BINSTAR_TOKEN: VdjdJuU4p0EJN2odZG5M+ig8GWMsDzxqsWLd9fhZ2IPrMPz6a4YvBRcQrbVaSDYo
azure:
  user_or_org: rvolz
